#pragma once

// languages.h — список языков стран для фильтра серверов.
// Первый элемент всегда "All" (все языки).
// aliases: разделённые '|' коды/названия (lowercase), которые присылают серверы
// (например "en|english|english - us"). Пустой aliases = без особых синонимов.

struct LanguageDef {
    const char *label;
    const char *aliases;
};

static const LanguageDef kLanguages[] = {
    { "All", "" },
    { "Arabic (Egypt)",          "ar|arabic" },
    { "Arabic (Middle-East)",    "ar|arabic" },
    { "Arabic (Morocco)",        "ar|arabic" },
    { "Armenian (Armenia)",      "hy|armenian" },
    { "Azerbaijani (Azerbaijan)","az|azerbaijani" },
    { "Belarusian (Belarus)",    "be|belarusian" },
    { "Bengali (Bangladesh)",    "bn|bengali" },
    { "Bulgarian (Bulgaria)",    "bg|bulgarian" },
    { "Burmese (Myanmar)",       "my|burmese" },
    { "Cantonese (China)",       "yue|cantonese" },
    { "Catalan (Spain)",         "ca|catalan" },
    { "Croatian (Croatia)",      "hr|croatian" },
    { "Czech (Czech Republic)",  "cs|czech" },
    { "Danish (Denmark)",        "da|danish" },
    { "Dutch (Netherlands)",     "nl|dutch" },
    { "English (Australia)",     "en|English|english - au|english us|english" },
    { "English (Canada)",        "en|English|english - ca|english us|english" },
    { "English (India)",         "en|English|english - in|english us|english" },
    { "English (United Kingdom)","en|English|english - uk|english us|english" },
    { "English (United States)", "en|English|english - us|english uk|english" },
    { "Estonian (Estonia)",      "et|estonian" },
    { "Farsi (Iran)",            "fa|farsi" },
    { "Filipino (Philippines)",  "fil|filipino" },
    { "Finnish (Finland)",       "fi|finnish" },
    { "French (Belgium)",        "fr|french - be|french" },
    { "French (Canada)",         "fr|french - ca|french" },
    { "French (France)",         "fr|french - fr|french" },
    { "French (Switzerland)",    "fr|french - ch|french" },
    { "Georgian (Georgia)",      "ka|georgian" },
    { "German (Austria)",        "de|german - at|german" },
    { "German (Germany)",        "de|german - de|german" },
    { "German (Switzerland)",    "de|german - ch|german" },
    { "Greek (Cyprus)",          "el|greek - cy|greek" },
    { "Greek (Greece)",          "el|greek - gr|greek" },
    { "Hebrew (Israel)",         "he|hebrew" },
    { "Hindi (India)",           "hi|hindi" },
    { "Hungarian (Hungary)",     "hu|hungarian" },
    { "Icelandic (Iceland)",     "is|icelandic" },
    { "Indonesian (Indonesia)",  "id|indonesian" },
    { "Italian (Italy)",         "it|italian - it|italian" },
    { "Italian (Switzerland)",   "it|italian - ch|italian" },
    { "Japanese (Japan)",        "ja|japanese" },
    { "Kazakh (Kazakhstan)",     "kk|kazakh" },
    { "Khmer (Cambodia)",        "km|khmer" },
    { "Korean (South Korea)",    "ko|korean" },
    { "Kurdish (Iraq)",          "ku|kurdish - iq|kurdish" },
    { "Kurdish (Turkey)",        "ku|kurdish - tr|kurdish" },
    { "Lao (Laos)",              "lo|lao" },
    { "Latvian (Latvia)",        "lv|latvian" },
    { "Lithuanian (Lithuania)",  "lt|lithuanian" },
    { "Macedonian (North Macedonia)", "mk|macedonian" },
    { "Malay (Malaysia)",        "ms|malay" },
    { "Maltese (Malta)",         "mt|maltese" },
    { "Mongolian (Mongolia)",    "mn|mongolian" },
    { "Montenegrin (Montenegro)","cnr|montenegrin" },
    { "Norwegian (Norway)",      "no|norwegian" },
    { "Pashto (Afghanistan)",    "ps|pashto" },
    { "Polish (Poland)",         "pl|polish" },
    { "Portuguese (Angola)",     "pt|portuguese - ao|portuguese" },
    { "Portuguese (Brazil)",     "pt|portuguese - br|portuguese" },
    { "Portuguese (Portugal)",   "pt|portuguese - pt|portuguese" },
    { "Punjabi (Pakistan)",      "pa|punjabi" },
    { "Punjabi (India)",         "pa|punjabi" },
    { "Romanian (Moldova)",      "ro|romanian - md|romanian" },
    { "Romanian (Romania)",      "ro|romanian - ro|romanian" },
    { "Russian (Russia)",        "ru|Russian|russian - ru|russian" },
    { "Serbian (Bosnia and Herzegovina)", "sr|serbian - ba|serbian" },
    { "Serbian (Serbia)",        "sr|serbian - rs|serbian" },
    { "Sinhala (Sri Lanka)",     "si|sinhala" },
    { "Slovak (Slovakia)",       "sk|slovak" },
    { "Slovenian (Slovenia)",    "sl|slovenian" },
    { "Spanish (Argentina)",     "es|spanish - ar|spanish" },
    { "Spanish (Chile)",         "es|spanish - cl|spanish" },
    { "Spanish (Colombia)",      "es|spanish - co|spanish" },
    { "Spanish (Latin America)", "es|spanish" },
    { "Spanish (Mexico)",        "es|spanish - mx|spanish" },
    { "Spanish (Peru)",          "es|spanish - pe|spanish" },
    { "Spanish (Spain)",         "es|spanish - es|spanish" },
    { "Swahili (Kenya)",         "sw|swahili - ke|swahili" },
    { "Swahili (Tanzania)",      "sw|swahili - tz|swahili" },
    { "Swedish (Sweden)",        "sv|swedish" },
    { "Tagalog (Philippines)",   "tl|tagalog" },
    { "Tajik (Tajikistan)",      "tg|tajik" },
    { "Tamil (India)",           "ta|tamil - in|tamil" },
    { "Tamil (Sri Lanka)",       "ta|tamil - lk|tamil" },
    { "Telugu (India)",          "te|telugu" },
    { "Thai (Thailand)",         "th|thai" },
    { "Turkish (Cyprus)",        "tr|turkish - cy|turkish" },
    { "Turkish (Turkey)",        "tr|turkish - tr|turkish" },
    { "Turkmen (Turkmenistan)",  "tk|turkmen" },
    { "Ukraine",                 "uk|ukrainian" },
    { "Urdu (India)",            "ur|urdu - in|urdu" },
    { "Urdu (Pakistan)",         "ur|urdu - pk|urdu" },
    { "Uzbek (Uzbekistan)",      "uz|uzbek" },
    { "Vietnamese (Vietnam)",    "vi|vietnamese" },
    { "Chinese (Simplified)",    "zh|chinese|中文|简体" },
    { "Chinese (Traditional)",   "zh|chinese|繁體|繁体" },
    { "Welsh (United Kingdom)",  "cy|welsh" },
    { "Zulu (South Africa)",     "zu|zulu" },
};

static const int kLanguageCount =
    (int)(sizeof(kLanguages) / sizeof(kLanguages[0]));